Task 20 internal error
hh-project17/safebox pull request #5
Opened 2017-05-03 14:16 UTC by Dkotlukov

Я выдаю "Internal Error", если запуск программы завершился с докеровским кодом ошибки. Или если произошла ошибка при создании контейнера.

2017-05-09 11:02 UTC, yaeuge requested changes
В целом, ок

Мне до сих пор не нравится, что все ошибки у нас проходят в итоге через stdout, но это не проблема этой таски

2017-05-09 11:02 UTC, yaeuge commented on src/main/java/ru/hh/safebox/app/DockerCmdBuilder.java
> +    private static final Logger LOG = LoggerFactory.getLogger(Util.class);
`DockerCmdBuilder.class`?

2017-05-09 11:02 UTC, yaeuge commented on src/main/java/ru/hh/safebox/util/Util.java
> +    private static final Set<Integer> DOCKER_ERRORS = new HashSet<>(Arrays.asList(125, 126, 127));
125, 126, 127 -- это исчерпывающий список? Возможно, какие-нибудь ещё коды самих программ тоже можно было бы отнести к внутренним ошибкам. Но я не знаю :)

2017-05-09 11:02 UTC, yaeuge commented on src/main/java/ru/hh/safebox/util/Util.java
>          }
Немного непрозрачная логика в этих if. Если они взаимоисключающие (а это точно так?), не лучше ли их будет перечислить через else-if?

2017-05-11 07:29 UTC, Dkotlukov commented on src/main/java/ru/hh/safebox/util/Util.java
> +    private static final Set<Integer> DOCKER_ERRORS = new HashSet<>(Arrays.asList(125, 126, 127));
Это иcчерпывающий список кодов, которые докер кидает по своей инициативе. Про ошибки программ я думал, но не придумал таких ситуаций.

2017-05-11 07:31 UTC, Dkotlukov commented on src/main/java/ru/hh/safebox/util/Util.java
>          }
поправил

2017-05-11 07:31 UTC, Dkotlukov commented on src/main/java/ru/hh/safebox/app/DockerCmdBuilder.java
> +    private static final Logger LOG = LoggerFactory.getLogger(Util.class);
поправил

2017-05-11 10:06 UTC, yaeuge approved these changes

2017-05-15 15:38 UTC, merged